### ISSUE TITLE
OFDM Estimator is not running on USRP X310

### ISSUE THREAD

**Issue by Ayush-IND** [gnuradio/gr-inspector#38] opened 2021-09-06 05:27 UTC
Hello all,

We are using OFDM Estimator grc in  GNU radio 3.8  with USRP X310 (UHD_4.0.0.0-206).

We are getting the following error and execution is getting terminated automatically.

Please provide the solution for the below problem/error.

"thread[thread-per-block[1]: <block ofdm_zkf_c(4)>]: cannot create std::vector larger than max_size()"

Thank you.

**Comment by kyz20** [comment] 2022-11-23 11:39
Did you solve this problem?

**Comment by marcusmueller** [comment] 2024-06-30 13:36
Duplicate of #48

**Closed as completed by marcusmueller** 2024-06-30 13:36 UTC
