### ISSUE TITLE
Provide working environment details

### ISSUE THREAD

**Issue by gammarf** [gnuradio/gr-inspector#19] opened 2018-04-06 22:26 UTC
Running Ubuntu l7.10, gnuradio 3.7.10.  Was difficult to install and the blocks do not work after installation.  Please provide documentation describing your working environment.

**Comment by sbmueller** [comment] 2018-04-07 08:41
@gammarf gr-inspector is not limited to my working environment. I used Fedora 24 and GNU Radio 3.7.9 but nevertheless, it should work in other environments, too. The dependencies are listed in the README.md.
If you have issues installing, please use the mailing list or email me directly. As stated in the README.md as well: 

**"Please only use GitHub issues for actual bugs and improvements! 'This command is not working on my machine' is not a bug."**

 Therefore I'm closing this.

**Closed as completed by sbmueller** 2018-04-07 08:41 UTC
