### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by ghost** [gnuradio/gr-inspector#22] opened 2018-05-10 19:51 UTC
Hi.
I installed all the dependencies but still get error.
What is the issue in here.
I am posting my terminal output.
Regards...
```
mustaphos@ubuntu64:~/Desktop$ cd gr-inspector
mustaphos@ubuntu64:~/Desktop/gr-inspector$ cd build
mustaphos@ubuntu64:~/Desktop/gr-inspector/build$ cmake ..
-- Build type not specified: defaulting to release.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- 
-- Python checking for PyQt4
-- Python checking for PyQt4 - found
-- Found QwtPlot3D-qt4: /usr/lib/libqwtplot3d-qt4.so
-- QWT Version: 6.1.2
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: ANALOG
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-analog.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so;/usr/lib/x86_64-linux-gnu/libvolk.so
GNURADIO_ANALOG_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-blocks.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: FFT
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-fft.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_FFT_FOUND = TRUE
Checking for GNU Radio Module: FILTER
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-filter.so;/usr/lib/x86_64-linux-gnu/libgnuradio-fft.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_FILTER_FOUND = TRUE
Checking for GNU Radio Module: PMT
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_PMT_FOUND = TRUE
Checking for GNU Radio Module: VOLK
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libvolk.so
GNURADIO_VOLK_FOUND = TRUE
-- Extracting version information from git describe...
-- Using install prefix: /usr/local
-- Building for version: 4bd982c8 / 1.1.2git
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.8.
-- Found SWIG: /usr/bin/swig3.0  
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mustaphos/Desktop/gr-inspector/build
mustaphos@ubuntu64:~/Desktop/gr-inspector/build$ sudo make -j4
Scanning dependencies of target _inspector_swig_doc_tag
[  5%] Built target pygen_python_0c7a7
[  5%] Built target pygen_apps_9a6dd
[  7%] Building CXX object swig/CMakeFiles/_inspector_swig_doc_tag.dir/_inspector_swig_doc_tag.cpp.o
[ 10%] Built target doxygen_target
[ 13%] Linking CXX executable _inspector_swig_doc_tag
[ 15%] Building CXX object lib/CMakeFiles/gnuradio-inspector.dir/ofdm_bouzegzi_c_impl.cc.o
[ 18%] Building CXX object lib/CMakeFiles/gnuradio-inspector.dir/ofdm_synchronizer_cc_impl.cc.o
[ 21%] Building CXX object lib/CMakeFiles/gnuradio-inspector.dir/ofdm_zkf_c_impl.cc.o
[ 21%] Built target _inspector_swig_doc_tag
Scanning dependencies of target inspector_swig_swig_doc
[ 23%] Generating doxygen xml for inspector_swig_doc docs
[ 26%] Generating python docstrings for inspector_swig_doc
[ 26%] Built target inspector_swig_swig_doc
Scanning dependencies of target _inspector_swig_swig_tag
[ 28%] Building CXX object swig/CMakeFiles/_inspector_swig_swig_tag.dir/_inspector_swig_swig_tag.cpp.o
[ 31%] Linking CXX executable _inspector_swig_swig_tag
[ 31%] Built target _inspector_swig_swig_tag
[ 34%] Generating inspector_swig.tag
Scanning dependencies of target inspector_swig_swig_2d0df
[ 36%] Building CXX object swig/CMakeFiles/inspector_swig_swig_2d0df.dir/inspector_swig_swig_2d0df.cpp.o
[ 39%] Linking CXX executable inspector_swig_swig_2d0df
Swig source
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_synchronizer_cc_impl.cc: In member function ‘virtual int gr::inspector::ofdm_synchronizer_cc_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_synchronizer_cc_impl.cc:119:16: error: expected primary-expression before ‘float’
       __GR_VLA(float, r_mag, noutput_items - d_fft_len - d_cp_len);
                ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_synchronizer_cc_impl.cc:119:23: error: ‘r_mag’ was not declared in this scope
       __GR_VLA(float, r_mag, noutput_items - d_fft_len - d_cp_len);
                       ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_synchronizer_cc_impl.cc:119:66: error: ‘__GR_VLA’ was not declared in this scope
       __GR_VLA(float, r_mag, noutput_items - d_fft_len - d_cp_len);
                                                                  ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc: In member function ‘float gr::inspector::ofdm_bouzegzi_c_impl::autocorr(const gr_complex*, int, int, int)’:
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:146:16: error: expected primary-expression before ‘float’
       __GR_VLA(float, m_vec, M);
                ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:146:23: error: ‘m_vec’ was not declared in this scope
       __GR_VLA(float, m_vec, M);
                       ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:146:31: error: ‘__GR_VLA’ was not declared in this scope
       __GR_VLA(float, m_vec, M);
                               ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:168:26: error: expected primary-expression before ‘,’ token
       __GR_VLA(gr_complex, pre, M);
                          ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:168:28: error: ‘pre’ was not declared in this scope
       __GR_VLA(gr_complex, pre, M);
                            ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc: In member function ‘float gr::inspector::ofdm_bouzegzi_c_impl::cost_func(const gr_complex*, int, int)’:
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:211:16: error: expected primary-expression before ‘float’
       __GR_VLA(float, power, 2 * d_Nb + 1);
                ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:211:23: error: ‘power’ was not declared in this scope
       __GR_VLA(float, power, 2 * d_Nb + 1);
                       ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:211:42: error: ‘__GR_VLA’ was not declared in this scope
       __GR_VLA(float, power, 2 * d_Nb + 1);
                                          ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:212:16: error: expected primary-expression before ‘float’
       __GR_VLA(float, R, 2 * d_Nb + 1);
                ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:212:23: error: ‘R’ was not declared in this scope
       __GR_VLA(float, R, 2 * d_Nb + 1);
                       ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc: In member function ‘std::vector<float> gr::inspector::ofdm_zkf_c_impl::autocorr(const gr_complex*, int)’:
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:80:26: error: expected primary-expression before ‘,’ token
       __GR_VLA(gr_complex, Rxx, len);
                          ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:80:28: error: ‘Rxx’ was not declared in this scope
       __GR_VLA(gr_complex, Rxx, len);
                            ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:80:36: error: ‘__GR_VLA’ was not declared in this scope
       __GR_VLA(gr_complex, Rxx, len);
                                    ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc: In member function ‘gr_complex* gr::inspector::ofdm_zkf_c_impl::tv_autocorr(const gr_complex*, int, int)’:
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:102:26: error: expected primary-expression before ‘,’ token
       __GR_VLA(gr_complex, corr_temp, len);
                          ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:102:28: error: ‘corr_temp’ was not declared in this scope
       __GR_VLA(gr_complex, corr_temp, len);
                            ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:102:42: error: ‘__GR_VLA’ was not declared in this scope
       __GR_VLA(gr_complex, corr_temp, len);
                                          ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc: In member function ‘virtual int gr::inspector::ofdm_zkf_c_impl::work(int, gr_vector_const_void_star&, gr_vector_void_star&)’:
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:182:16: error: expected primary-expression before ‘float’
       __GR_VLA(float, result, fft_len); // magnitude of CCF
                ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:182:23: error: ‘result’ was not declared in this scope
       __GR_VLA(float, result, fft_len); // magnitude of CCF
                       ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:182:38: error: ‘__GR_VLA’ was not declared in this scope
       __GR_VLA(float, result, fft_len); // magnitude of CCF
                                      ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:187:16: error: expected primary-expression before ‘float’
       __GR_VLA(float, d_tmpbuf, fft_len / 2);
                ^
/home/mustaphos/Desktop/gr-inspector/lib/ofdm_zkf_c_impl.cc:187:23: error: ‘d_tmpbuf’ was not declared in this scope
       __GR_VLA(float, d_tmpbuf, fft_len / 2);
                       ^
lib/CMakeFiles/gnuradio-inspector.dir/build.make:336: recipe for target 'lib/CMakeFiles/gnuradio-inspector.dir/ofdm_synchronizer_cc_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-inspector.dir/ofdm_synchronizer_cc_impl.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
lib/CMakeFiles/gnuradio-inspector.dir/build.make:288: recipe for target 'lib/CMakeFiles/gnuradio-inspector.dir/ofdm_bouzegzi_c_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-inspector.dir/ofdm_bouzegzi_c_impl.cc.o] Error 1
lib/CMakeFiles/gnuradio-inspector.dir/build.make:312: recipe for target 'lib/CMakeFiles/gnuradio-inspector.dir/ofdm_zkf_c_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-inspector.dir/ofdm_zkf_c_impl.cc.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'lib/CMakeFiles/gnuradio-inspector.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-inspector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 39%] Built target inspector_swig_swig_2d0df
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sbmueller** [comment] 2018-05-11 13:55
Hello @mustaphos 
I want to point out that you obviously didn't read the README, where clearly is stated:
"If you run into problems installing or using gr-inspector, the GNU Radio mailing list is the right place to get help. [...] Please only use GitHub issues for actual bugs and improvements! 'This command is not working on my machine' is not a bug." Therefore I'm closing this issue.

A short search on your error message on the mailing list however revealed a potential solution [1]. Please refer to the mailing list in the future for issues like that.

[1] http://lists.gnu.org/archive/html/discuss-gnuradio/2018-04/msg00143.html

**Closed as completed by sbmueller** 2018-05-11 13:55 UTC

**Comment by sbmueller** [comment] 2018-05-11 14:01
I've followed the mailing list advice and edited the README to make clear that only GNU Radio versions greater equal 3.7.9.3 are supported.
